### ISSUE TITLE
Ontology error

### ISSUE THREAD

**Issue by bnymnsen** [HUBioDataLab/CROssBAR-BioCypher-Migration#9]
Hi @slobentanzer,

After adding Interpro data to `create_crossbar.py`, I faced following issue:

```
Traceback (most recent call last):
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\create_crossbar.py", line 150, in <module>
    main()
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\create_crossbar.py", line 133, in main
    bc.write_nodes(uniprot_adapter.get_nodes())
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\biocypher\_core.py", line 239, in write_nodes
    self._get_writer()
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\biocypher\_core.py", line 204, in _get_writer
    ontology=self._get_ontology(),
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\biocypher\_core.py", line 186, in _get_ontology
    self._ontology = Ontology(
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\biocypher\_ontology.py", line 283, in __init__
    self._main()
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\biocypher\_ontology.py", line 301, in _main
    self._extend_ontology()
  File "d:\crossbar\CROssBAR-BioCypher-Migration\scripts\biocypher\_ontology.py", line 421, in _extend_ontology
    raise ValueError(
ValueError: Node protein to protein domain association not found in ontology, but also has no inheritance definition. Please check your schema for spelling errors or a missing `is_a` definition.
```
I didn't encounter this problem while creating CROssBAR with my earlier version (Now, I am using latest version of BioCypher to create it). How to solve this problem? Should I add `is_a` to related association, if so what to add?

**Comment by slobentanzer** [comment]
Yes, this is a decision I made (somewhat arbitrarily) to have all entities situated in the ontology. It is not set in stone that this will remain mandatory as it is now, maybe we will soften it to a warning. But for now, to remove the error, we need to make sure that all entities are accounted for in the ontological framework in some way. In this case, this would be an `is_a` inheritance; I mostly just add the plain `association`, but you can build a hierarchy as well, if that applies to your use case.

The other way around (having it as just a warning) can lead to other, more opaque errors in places where it isn't necessarily obvious that the ontology tree is the problem, so I added this check at instantiation that asserts consistency of the ontology structure.
